#워크플로우 이름
name: ftp_deploy
# 이벤트 생성하기
on: 
  # 이벤트를 수동으로 실행 (main brainch에 push 가 되었을때 실행하겠다는 의미)
  workflow_dispatch:
  push:
    branches: 
      - main
# 워크플로우가 수행할 작업
jobs:
  # 작업의 이름
  upload:
    # 작업을 실행할 환경 (리눅스 우분투)
    runs-on: ubuntu-latest
    # 실행 단계
    steps:
    - name: checkout repository
      # 깃허브에서 실행한 환경으로 코드 내려받기
      uses: actions/checkout@v3

    - name: install lftp
      # ftp 업로드에 필요한 프로그램 설치 (sudo - 관리자권한으로 실행, apt-get 패키지 설치)
      run: sudo apt-get install -y lftp
    - name: Upload files via ftp
      run:
        lftp -u ${{ secrets.SFTP_USER }},${{ secrets.SFTP_PASSWORD }} -e "set ftp:ssl-allow no; mirror -R ./ /html/project_1; bye" ftp://${{ secrets.SFTP_HOST }}:${{ secrets.SFTP_PORT }}
